// SPDX-License-Identifier: BSD-3-Clause

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// SetupKeySpecApplyConfiguration represents a declarative configuration of the SetupKeySpec type for use
// with apply.
//
// SetupKeySpec defines the desired state of SetupKey.
type SetupKeySpecApplyConfiguration struct {
	// Name of the setup key.
	Name *string `json:"name,omitempty"`
	// Ephemeral decides if peers added with the key are ephemeral or not.
	Ephemeral *bool `json:"ephemeral,omitempty"`
	// AllowExtraDnsLabels decides if peers added with the key can have extra DNS labels.
	AllowExtraDnsLabels *bool `json:"allowExtraDnsLabels,omitempty"`
	// Duration sets how long the setup key is valid for.
	Duration *v1.Duration `json:"duration,omitempty"`
	// AutoGroups are groups that will be automatically assigned to peers using setup key.
	AutoGroups []GroupReferenceApplyConfiguration `json:"autoGroups,omitempty"`
}

// SetupKeySpecApplyConfiguration constructs a declarative configuration of the SetupKeySpec type for use with
// apply.
func SetupKeySpec() *SetupKeySpecApplyConfiguration {
	return &SetupKeySpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SetupKeySpecApplyConfiguration) WithName(value string) *SetupKeySpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithEphemeral sets the Ephemeral field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ephemeral field is set to the value of the last call.
func (b *SetupKeySpecApplyConfiguration) WithEphemeral(value bool) *SetupKeySpecApplyConfiguration {
	b.Ephemeral = &value
	return b
}

// WithAllowExtraDnsLabels sets the AllowExtraDnsLabels field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowExtraDnsLabels field is set to the value of the last call.
func (b *SetupKeySpecApplyConfiguration) WithAllowExtraDnsLabels(value bool) *SetupKeySpecApplyConfiguration {
	b.AllowExtraDnsLabels = &value
	return b
}

// WithDuration sets the Duration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Duration field is set to the value of the last call.
func (b *SetupKeySpecApplyConfiguration) WithDuration(value v1.Duration) *SetupKeySpecApplyConfiguration {
	b.Duration = &value
	return b
}

// WithAutoGroups adds the given value to the AutoGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AutoGroups field.
func (b *SetupKeySpecApplyConfiguration) WithAutoGroups(values ...*GroupReferenceApplyConfiguration) *SetupKeySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAutoGroups")
		}
		b.AutoGroups = append(b.AutoGroups, *values[i])
	}
	return b
}
